<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_width" value="0.05"/>
    <xacro:property name="camera_length" value="0.05"/>
    <xacro:property name="camera_height" value="0.05"/>

    <link name="camera_link">
        <visual>
        <origin xyz = "0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${camera_width} ${camera_length} ${camera_height}"/>
        </geometry>
        <material name = "red"/>
        </visual>

        <collision>
            <origin xyz = "0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="0.5"  l = "${2*camera_length}" 
                                    w ="${2*camera_width}" 
                                    h = "${2*camera_height}"
                                    xyz = "0 0 0"
                                    rpy = "0 0 0" />
 
    </link>

    <joint name="base_to_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.3 0 0" rpy="0 0 0" /> 
    </joint>

    <gazebo reference = "camera_link">
        <sensor name = "camera_sensor" type = "camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frameName>camera_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>