<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_width" value="0.6" />
    <xacro:property name="base_length" value="0.4" />
    <xacro:property name="base_height" value="0.2" />

    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:property name="caster_wheel_radius" value="0.05" />


    <link name = "base_footprint" />

    <link name = "base_link" >
        <visual>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <geometry>
                 <box size = "${base_width} ${base_length} ${base_height}"/>  <!-- width, length, height-->
            </geometry>
            <material name="cyan"/>
        </visual>

        <collision>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <geometry>
                <box size = "${base_width} ${base_length} ${base_height}"/>  
            </geometry>
        </collision>

        <xacro:box_inertia m="5.0"  l = "${2*base_length}" 
                                    w ="${2*base_width}" 
                                    h = "${2*base_height}"
                                    xyz = "0 0 0"
                                    rpy = "0 0 0" />
    </link>

    <joint name="base_footprint_to_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${(base_height/2)+(wheel_radius)}" rpy="0 0 0" /> 
    </joint>


    <xacro:macro name="wheel_link" params="prefix reflect">
        <link name = "${prefix}_wheel_link" >
            <visual>
                <origin xyz = "0 0 0" rpy = "${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz = "0 0 0" rpy = "${pi/2} 0 0 "/>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
            </collision>
             <xacro:cylinder_inertia m="1.0" r = "${2*wheel_radius}" 
                                             l ="${2*wheel_length}" 
                                             xyz = "0 0 0"
                                             rpy = "${pi/2} 0 0" />
        </link>

        <joint name="base_to_${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${(-(base_width/2)) + (wheel_radius)} ${reflect * ((base_length/2) + (wheel_length/2))} ${(-(wheel_radius))}"/>
            <axis xyz="0 1 0"/>
        </joint>

    </xacro:macro>

    <xacro:wheel_link prefix="right" reflect="1" />
    <xacro:wheel_link prefix="left" reflect="-1" />


    <link name = "caster_wheel_link" >
        <visual>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <geometry>
                 <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
             <geometry>
                 <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:sphere_inertia m="0.5" r = "${2*caster_wheel_radius}"
                                      xyz = "0 0 0"
                                      rpy = "0 0 0" />
    </link>

    <joint name="base_to_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="0.2 0 ${-((base_height/2) + (caster_wheel_radius))}" rpy="0 0 0" /> 
    </joint>


</robot>